services:
  postgres:
    image: 'postgres:latest'
    container_name: tab-registration-dev
    environment:
      - 'POSTGRES_DB=tab_registration_dev'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5431:5432'
