spring:
  application:
    name: registration_service
  security:
    user:
      name: swaggeruser
      password: ${SWAGGER_PASSWORD:changeme}
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,loggers,beans
  endpoint:
    health:
      show-details: always
server:
  servlet:
    context-path: /registration-service